version: '3.8'

services:
  # Box项目的后端服务
  box-backend:
    image: box_p-backend
    container_name: box-backend
    restart: unless-stopped
    environment:
      - DEBUG=True  # 启用DEBUG以便查看错误信息
      - ALLOWED_HOSTS=localhost,127.0.0.1,box-backend,nginx,192.168.137.134
      - APPEND_SLASH=False  # 关闭尾斜杠追加，适配前端请求
    networks:
      - app-network

  # P2P项目的后端服务
  p2p-backend:
    image: p2p-backend
    container_name: p2p-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5235
      - ALLOWED_ORIGINS=http://localhost
    networks:
      - app-network
      
  # Student项目的后端服务
  student-backend:
    image: student-backend
    container_name: student-backend
    restart: unless-stopped
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,student-backend,nginx
    networks:
      - app-network

  # Nginx服务 - 处理所有应用的路由
  nginx:
    image: nginx:alpine
    container_name: integrated-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./box/box_show/build:/usr/share/nginx/html/box
      - ./P2P/p2p-client/build:/usr/share/nginx/html/p2p
      - ./Student_Enroll_Grade_System/front_end/dist:/usr/share/nginx/html
      - ./test.html:/usr/share/nginx/html/test.html
    depends_on:
      - box-backend
      - p2p-backend
      - student-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
