# Generated by Django 5.0.3 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_item_id_item_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
